require_relative '../../node_modules/react-native-test-app/test_app'

use_flipper! false

workspace 'theme-control-example.xcworkspace'

use_test_app! :fabric_enabled => false, :turbomodule_enabled => false
